### ISSUE TITLE
Missing type: bounds

### ISSUE THREAD

**Issue by JohnTM** [TwoLivesLeft/Codea-Documentation#8]
`bounds`

A geometric utility type representing the rectangular bounding volume. Create a new bounds by giving it a minimum and maximum range as `vec3()`s

`b = bounds(min, max)`
`b = bounds(vec3(0, 0, 0), vec3(1, 1, 1))`

*Properties:*
- `min` vec3, the minimum x,y,z range of the area encapsulated by the bounding volume
- `max` vec3, the maximum x,y,z range of the area encapsulated by the bounding volume
- `valid` boolean, whether or not this bounds is valid (i.e. has zero or greater volume)
- `center` vec3, the center of the volume (i.e. half way between `min` and `max`)
- `offset` vec3, the offset of the volume (i.e. `min`)
- `size` vec3, the size of the volume (i.e. `max - min`)

*Methods:*
- `intersects(other)` boolean, checks to see if this bounding volume intersects another
- `intersects(origin, dir)` boolean, checks to see if this bounding is intersected by the given ray
- `encapsulate(point)` expands the bounds to include the given point
- `translate(offset)` moves the bounds by the given offset
- `set(min, max)` reset the bounds given new min and max values

**Comment by TwoLivesLeft** [comment]
This is fixed in the following PR:

https://github.com/TwoLivesLeft/Codea-Documentation/pull/9

Please take a look and let me know if all good to merge (I invited you as a collaborator so I'll add you directly to this and future PRs once you've accepted)
